# Generated by Django 2.0.4 on 2018-07-16 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180716_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filled', to='main.DocumentTemplate', verbose_name='Шаблон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_name',
            field=models.CharField(choices=[('practice_diary', 'Дневник практики'), ('inner_individual_task', 'Индивидуальное задание (внутренняя практика)'), ('outer_individual_task', 'Индивидуальное задание (внешняя практика)'), ('inner_report_title', 'Титульный лист отчёта (внутренняя практика)'), ('outer_report_title', 'Титульный лист отчёта (внешняя практика)')], max_length=100, unique=True, verbose_name='Уникальный ключ документа'),
        ),
    ]
