# Generated by Django 2.0.4 on 2018-07-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180716_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('template', 'student', 'practice')},
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
