# Generated by Django 2.0.7 on 2018-07-19 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180717_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatorprofile',
            name='academic_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ученое звание'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to=main.models.get_only_students_q_without_profile, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studenttopractice',
            name='student',
            field=models.ForeignKey(limit_choices_to=main.models.get_only_students_q_with_profile, on_delete=django.db.models.deletion.CASCADE, related_name='student_relations', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
