# Generated by Django 2.0.7 on 2018-07-11 22:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180711_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Заполненные документы'},
        ),
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'verbose_name_plural': 'Шаблоны документов'},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'verbose_name_plural': 'Практики'},
        ),
        migrations.AlterModelOptions(
            name='studenttopractice',
            options={'verbose_name_plural': 'Связи студентов к практикам'},
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to=main.models.avatars_directory),
        ),
    ]
