# Generated by Django 2.0.4 on 2018-07-16 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180716_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='practice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practice_documents', to='main.Practice', verbose_name='Практика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='student',
            field=models.ForeignKey(limit_choices_to=main.models.get_only_students_q, on_delete=django.db.models.deletion.CASCADE, related_name='student_documents', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
