# Generated by Django 2.0.4 on 2018-07-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180716_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
