# Generated by Django 2.0.4 on 2018-07-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_document_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'На проверке'), (1, 'Принят'), (2, 'Отклонен')], default=0),
        ),
    ]
